language: node_js
env:
  - debug=*
before_script:
  - unset FSD_COVERAGE
  - gulp test
#  - gulp instrument
node_js:
 - 12
after_script:
  - tsc
  - npm run coveralls
  - npm run coverallsX

