language: node_js
env:
  - debug=*
before_script:
  - unset FSD_COVERAGE
  - gulp tsc
  - npm run test
  - unset DEBUG
  - gulp
  - tsc
#  - gulp instrument
node_js:
 - "12"
after_script:
#  - npm run coverage
  - npm run coveralls

