language: node_js
before_script:
  - unset FSD_COVERAGE
  - gulp tsc
  - set DEBUG=*
  - nodeunit test\parser.nunit.js -t testCatListMoreInFactAndFact2
  - gulp
  - tsc
#  - gulp instrument
node_js:
 - "8"
 - "node"
after_script:
  - npm run coverage
  - npm run coveralls

