@rem critical
set MONGO_RECORD_REPLAY=


SET MGNLQ_TESTMODEL_REPLAY=
SET MGNLQ_RECORD_REPLAY=
SET MONGO_TEST_RECORD=
SET MONGO_TEST_REPORT=

SET ABOT_MODELPATH=

TITLE mgnql_parser1_env_plain
COLOR 07